### PR TITLE
Merge pull request #1 from igromanru/dev

### PR DESCRIPTION
**Pull request by zanzo420**
Added Pigs/Snakes/Skull Forts, as well as fixed a typo in offsets.h

### CODE REVIEW

**Comment by igromanru** [comment]
There are no changes??
You have just merged my changes into your fork.

**Comment by zanzo420** [comment]
I am new to this whole GitHub thing, yes that was suppose to just be me merging ur recent changes to my fork... but it also includes the addition of pigs/snakes, skeleton forts, and treasure artifacts to the esp... at least its added in my code

**Comment by igromanru** [comment]
For next time:
You have to commit your changes first, then merge my branch into yours, then make a pull request.

**Comment by zanzo420** [comment]
ok, thank you... I'll make sure to do that next time.

**Pull request closed without merging**
